/**
 * The realm table — the tuning knobs, and nothing else.
 *
 * One row per world. This is the file you open to add a world or to move a
 * quantity; the placement algorithm lives in `build.js` and the difficulty
 * ramps in `curve.js`. Nothing here is served to the browser: the game reads
 * the level database, never the generator.
 */

import { KIND } from '../prototype/src/core/block.js';

/**
 * A realm spans twenty levels and is defined by a single row of the table
 * below. It brings the player three things, always all three together:
 *
 *  1. A NOVELTY — a block kind, or a rule, they have never seen.
 *  2. A PALETTE — the six families keep their glyphs (●◆▲★■⬢), which carry the
 *     rule, but change hue: the realm is recognisable at a glance without
 *     block/gate matching having to be relearnt.
 *  3. A STEP UP IN DIFFICULTY — a bigger grid, one more colour or gate, and
 *     above all a capacity margin that keeps tightening.
 *
 * Twenty levels per realm rather than five: a new mechanic needs practising
 * before it is combined with the next one. Difficulty rises WITHIN a realm (the
 * quantities written `[start, end]` are interpolated over its twenty levels)
 * and steps up BETWEEN realms.
 */
export const LEVELS_PER_REALM = 20;

export const REALMS = [
  {
    id: 0, tier: 'tutorial',
    name: { fr: 'Peaceful Sakura', en: 'Peaceful Sakura', es: 'Peaceful Sakura', it: 'Peaceful Sakura', zh: 'Peaceful Sakura' },
    difficulty: { fr: 'apprentissage', en: 'learning the ropes', es: 'aprendizaje', it: 'apprendistato', zh: '入门' },
    hue: 345,
    palette: ['#eb9aad', '#93bde4', '#97cfb6', '#e9cd8c', '#bdaadd', '#f0b18b'],
    novelty: null,
    introduces: { fr: 'Les blocs et leurs portes', en: 'Blocks and their gates', es: 'Los bloques y sus puertas', it: 'I blocchi e le loro porte', zh: '方块与它们的门' },
    W: 5, H: 5, colorCount: 3, gateCount: 3,
    walls: [0, 0], locks: [0, 0], rails: [0, 0], anchors: [0, 0], bulky: [0, 0],
    jokers: 0, margin: null, colorSeal: false,
  },
  {
    id: 1, tier: 'gentle',
    name: { fr: 'Wisteria Veil', en: 'Wisteria Veil', es: 'Wisteria Veil', it: 'Wisteria Veil', zh: 'Wisteria Veil' },
    difficulty: { fr: 'facile', en: 'easy', es: 'fácil', it: 'facile', zh: '简单' },
    hue: 275,
    palette: ['#e8907b', '#7fb0c9', '#a9c48b', '#edc073', '#c39fc0', '#d9a06b'],
    novelty: KIND.RAIL,
    introduces: { fr: 'Blocs sur glissière, portes à capacité', en: 'Blocks on rails, gates with a capacity', es: 'Bloques sobre raíles, puertas con capacidad', it: 'Blocchi su binario, porte con capienza', zh: '滑轨方块，限量的门' },
    W: 6, H: 6, colorCount: 4, gateCount: 4,
    walls: [0, 1], locks: [0, 0], rails: [1, 5], anchors: [0, 0], bulky: [0, 0],
    jokers: 0, margin: 1, colorSeal: false,
  },
  {
    id: 2, tier: 'gentle',
    name: { fr: 'Blue Lys', en: 'Blue Lys', es: 'Blue Lys', it: 'Blue Lys', zh: 'Blue Lys' },
    difficulty: { fr: 'moyen', en: 'medium', es: 'medio', it: 'medio', zh: '中等' },
    hue: 225,
    palette: ['#d99aa8', '#8cc6e0', '#8fd3c4', '#d7d295', '#aeb3e0', '#e2b3a6'],
    novelty: KIND.WALL,
    introduces: { fr: 'Blocs scellés, immobiles', en: 'Sealed blocks that never move', es: 'Bloques sellados, inmóviles', it: 'Blocchi sigillati, immobili', zh: '封死不动的方块' },
    W: 6, H: 7, colorCount: 4, gateCount: 4,
    walls: [1, 4], locks: [0, 0], rails: [2, 6], anchors: [0, 0], bulky: [0, 0],
    jokers: 0, margin: 1, colorSeal: false,
  },
  {
    id: 3, tier: 'steady',
    name: { fr: 'Forget Me Not', en: 'Forget Me Not', es: 'Forget Me Not', it: 'Forget Me Not', zh: 'Forget Me Not' },
    difficulty: { fr: 'soutenu', en: 'steady', es: 'sostenido', it: 'sostenuto', zh: '进阶' },
    hue: 200,
    palette: ['#e493b4', '#8fa8e2', '#86cbb0', '#e3c886', '#b49ae0', '#7fc4d4'],
    novelty: KIND.LOCKED,
    introduces: { fr: 'Verrous à décompte', en: 'Locks with a countdown', es: 'Cerrojos con cuenta atrás', it: 'Serrature con conto alla rovescia', zh: '带计数的锁' },
    W: 6, H: 8, colorCount: 5, gateCount: 5,
    walls: [1, 4], locks: [1, 3], rails: [3, 7], anchors: [0, 0], bulky: [0, 0],
    jokers: 0, margin: 0, colorSeal: false,
  },
  {
    id: 4, tier: 'steady',
    name: { fr: 'Eucalyptus Calm', en: 'Eucalyptus Calm', es: 'Eucalyptus Calm', it: 'Eucalyptus Calm', zh: 'Eucalyptus Calm' },
    difficulty: { fr: 'exigeant', en: 'demanding', es: 'exigente', it: 'impegnativo', zh: '考验' },
    hue: 145,
    palette: ['#dd9b95', '#96b6cc', '#9fc9a4', '#d9bd7f', '#b2a6c9', '#e0a97f'],
    novelty: KIND.JOKER,
    introduces: { fr: 'Le joker, qui sort par où il veut', en: 'The joker, which leaves by any gate', es: 'El comodín, que sale por donde quiere', it: 'Il jolly, che esce da dove vuole', zh: '万能方块，任意门皆可' },
    W: 6, H: 8, colorCount: 5, gateCount: 5,
    walls: [2, 4], locks: [1, 3], rails: [4, 9], anchors: [0, 0], bulky: [0, 0],
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 5, tier: 'steady',
    name: { fr: 'Mimosa Sun', en: 'Mimosa Sun', es: 'Mimosa Sun', it: 'Mimosa Sun', zh: 'Mimosa Sun' },
    difficulty: { fr: 'redoutable', en: 'formidable', es: 'temible', it: 'temibile', zh: '棘手' },
    hue: 55,
    palette: ['#ec9cc0', '#8ec7d9', '#93cf8e', '#dfd083', '#c1a3dc', '#efb28f'],
    novelty: KIND.ANCHOR,
    introduces: { fr: 'Ancres, qui n’avancent que vers leur porte', en: 'Anchors, which only move towards their gate', es: 'Anclas, que solo avanzan hacia su puerta', it: 'Ancore, che avanzano solo verso la loro porta', zh: '锚块，只朝自己的门前进' },
    W: 7, H: 8, colorCount: 6, gateCount: 6,
    walls: [2, 5], locks: [1, 3], rails: [4, 9], anchors: [1, 4], bulky: [0, 0],
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 6, tier: 'steady',
    name: { fr: 'Golden Ginkgo', en: 'Golden Ginkgo', es: 'Golden Ginkgo', it: 'Golden Ginkgo', zh: 'Golden Ginkgo' },
    difficulty: { fr: 'implacable', en: 'relentless', es: 'implacable', it: 'implacabile', zh: '严苛' },
    hue: 40,
    palette: ['#d792bb', '#8bacdf', '#8ecdc0', '#e6cd90', '#a99ae0', '#e5a3a0'],
    novelty: KIND.BULKY,
    introduces: { fr: 'Encombrants, qui coûtent double à leur porte', en: 'Heavy blocks, which cost their gate double', es: 'Voluminosos, que cuestan el doble a su puerta', it: 'Ingombranti, che costano il doppio alla loro porta', zh: '笨重方块，占用双倍容量' },
    W: 7, H: 8, colorCount: 6, gateCount: 6,
    walls: [3, 5], locks: [2, 3], rails: [5, 10], anchors: [2, 5], bulky: [1, 4],
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 7, tier: 'steady',
    name: { fr: 'Autumn Elm', en: 'Autumn Elm', es: 'Autumn Elm', it: 'Autumn Elm', zh: 'Autumn Elm' },
    difficulty: { fr: 'intransigeant', en: 'unyielding', es: 'intransigente', it: 'intransigente', zh: '严厉' },
    hue: 25,
    palette: ['#ef8fa6', '#85b8e8', '#8ad4b1', '#f0cd7e', '#b99ae6', '#f4ab84'],
    novelty: 'color-seal',
    introduces: { fr: 'Des scellés qui attendent qu’une couleur ait disparu', en: 'Seals that wait for a whole colour to be gone', es: 'Sellos que esperan a que un color desaparezca', it: 'Sigilli che attendono la scomparsa di un colore', zh: '颜色封印：某色清空才解锁' },
    W: 8, H: 8, colorCount: 6, gateCount: 7,
    walls: [3, 6], locks: [2, 4], rails: [6, 12], anchors: [3, 6], bulky: [2, 5],
    // This realm used to close the game, and its tuning said so: no joker, not
    // an inch of margin. Once it became the eighth of eighteen, that mid-run
    // spike made the four realms after it feel easier than itself. Exact gate
    // capacity therefore belongs to the very last realm, where it belongs.
    jokers: 1, margin: 0, colorSeal: true,
  },
  {
    id: 8, tier: 'steady',
    name: { fr: 'Winter Maple', en: 'Winter Maple', es: 'Winter Maple', it: 'Winter Maple', zh: 'Winter Maple' },
    difficulty: { fr: 'retors', en: 'crafty', es: 'retorcido', it: 'insidioso', zh: '刁钻' },
    hue: 5,
    palette: ['#e0a08e', '#8fb9d6', '#a3ca9a', '#e3c37f', '#b7a4d4', '#dfa77f'],
    novelty: KIND.DUAL,
    introduces: { fr: 'Blocs bicolores, qui hésitent entre deux portes', en: 'Two-colour blocks, torn between two gates', es: 'Bloques bicolores, que dudan entre dos puertas', it: 'Blocchi bicolori, indecisi fra due porte', zh: '双色方块，可走两种门' },
    W: 8, H: 8, colorCount: 6, gateCount: 7,
    walls: [3, 6], locks: [2, 4], rails: [6, 12],
    anchors: [3, 6], bulky: [2, 5], duals: [1, 4],
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 9, tier: 'steady',
    name: { fr: 'Apple Blossom', en: 'Apple Blossom', es: 'Apple Blossom', it: 'Apple Blossom', zh: 'Apple Blossom' },
    difficulty: { fr: 'serré', en: 'tight', es: 'ajustado', it: 'stretto', zh: '局促' },
    hue: 30,
    palette: ['#dd8f96', '#8aa9cc', '#93c197', '#dcbd7c', '#ac9ccc', '#dc9d84'],
    novelty: 'narrow-gate',
    introduces: { fr: 'Des portes de deux cases, jamais plus', en: 'Gates two cells wide, never more', es: 'Puertas de dos casillas, nunca más', it: 'Porte di due caselle, mai di più', zh: '门宽只有两格' },
    W: 8, H: 8, colorCount: 6, gateCount: 7,
    walls: [4, 6], locks: [3, 4], rails: [7, 12],
    anchors: [4, 7], bulky: [3, 6], duals: [1, 3],
    wideGateRatio: 0.0,
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 10, tier: 'dense',
    name: { fr: 'Quiet Camellia', en: 'Quiet Camellia', es: 'Quiet Camellia', it: 'Quiet Camellia', zh: 'Quiet Camellia' },
    difficulty: { fr: 'massif', en: 'massive', es: 'macizo', it: 'massiccio', zh: '厚重' },
    hue: 345,
    palette: ['#d18fa8', '#7fa4d8', '#87c3ae', '#d9c084', '#a396d6', '#d59a94'],
    novelty: 'large-shapes',
    introduces: { fr: 'Plus une seule pièce d’une case', en: 'Not a single one-cell piece left', es: 'Ni una sola pieza de una casilla', it: 'Non più un solo pezzo da una casella', zh: '不再有单格方块' },
    W: 9, H: 8, colorCount: 6, gateCount: 7,
    walls: [3, 6], locks: [3, 4], rails: [7, 13],
    anchors: [4, 7], bulky: [3, 6], duals: [1, 3],
    minShapeSize: 2, density: [0.26, 0.33],
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 11, tier: 'dense',
    name: { fr: 'Lilac Drift', en: 'Lilac Drift', es: 'Lilac Drift', it: 'Lilac Drift', zh: 'Lilac Drift' },
    difficulty: { fr: 'trompeur', en: 'deceptive', es: 'engañoso', it: 'ingannevole', zh: '迷惑' },
    hue: 275,
    palette: ['#cf94a4', '#84b4cc', '#8fc98f', '#d4c286', '#a89dd0', '#d9a68a'],
    novelty: 'shared-gate',
    introduces: { fr: 'Des portes qui servent deux couleurs à la fois', en: 'Gates serving two colours at once', es: 'Puertas que sirven a dos colores a la vez', it: 'Porte che servono due colori insieme', zh: '一门通两色' },
    W: 9, H: 8, colorCount: 6, gateCount: 7,
    walls: [4, 6], locks: [3, 5], rails: [7, 13],
    anchors: [4, 7], bulky: [3, 6], duals: [1, 3],
    sharedGates: [1, 3],
    jokers: 1, margin: 0, colorSeal: false,
  },
  {
    id: 12, tier: 'dense',
    name: { fr: 'Cornflower Blue', en: 'Cornflower Blue', es: 'Cornflower Blue', it: 'Cornflower Blue', zh: 'Cornflower Blue' },
    difficulty: { fr: 'méthodique', en: 'methodical', es: 'metódico', it: 'metodico', zh: '讲究次序' },
    hue: 225,
    palette: ['#d68fb0', '#8ba6d4', '#8ccbb4', '#dfc57f', '#ab97d8', '#e0a292'],
    novelty: 'key',
    introduces: { fr: 'Une clé, dont la sortie ouvre tous les verrous', en: 'A key whose exit opens every lock', es: 'Una llave cuya salida abre todos los cerrojos', it: 'Una chiave la cui uscita apre tutte le serrature', zh: '一把钥匙，出门即开所有锁' },
    W: 9, H: 9, colorCount: 6, gateCount: 7,
    walls: [4, 6], locks: [3, 5], rails: [7, 13],
    anchors: [4, 7], bulky: [3, 6], duals: [1, 3],
    sharedGates: [2, 3], density: [0.26, 0.34],
    jokers: 1, margin: 0, colorSeal: false, key: true, largeShapes: true,
  },
  {
    id: 13, tier: 'dense',
    name: { fr: 'Morning Glory', en: 'Morning Glory', es: 'Morning Glory', it: 'Morning Glory', zh: 'Morning Glory' },
    difficulty: { fr: 'étouffant', en: 'stifling', es: 'asfixiante', it: 'soffocante', zh: '拥塞' },
    hue: 200,
    palette: ['#cd8c9e', '#7fa8c8', '#84c2a4', '#d3bd7a', '#a291cc', '#d29a88'],
    novelty: null,
    introduces: { fr: 'Des grilles remplies aux trois quarts', en: 'Grids packed three quarters full', es: 'Cuadrículas llenas en tres cuartos', it: 'Griglie piene per tre quarti', zh: '棋盘塞满四分之三' },
    W: 9, H: 9, colorCount: 6, gateCount: 8,
    walls: [4, 7], locks: [3, 5], rails: [8, 14],
    anchors: [5, 8], bulky: [3, 7], duals: [1, 3],
    sharedGates: [1, 2], density: [0.27, 0.35],
    jokers: 1, margin: 0, colorSeal: false, largeShapes: true,
  },
  {
    id: 14, tier: 'demanding',
    name: { fr: 'Sage Fern', en: 'Sage Fern', es: 'Sage Fern', it: 'Sage Fern', zh: 'Sage Fern' },
    difficulty: { fr: 'éprouvant', en: 'punishing', es: 'duro', it: 'duro', zh: '磨人' },
    hue: 145,
    palette: ['#dba38c', '#8fb2c4', '#9ec69b', '#dcc07e', '#b19dc8', '#d9a17e'],
    novelty: null,
    introduces: { fr: 'Tous les blocs du jeu, dans la même grille', en: 'Every block in the game, on one grid', es: 'Todos los bloques del juego en una misma cuadrícula', it: 'Tutti i blocchi del gioco, nella stessa griglia', zh: '所有方块类型齐聚一盘' },
    W: 9, H: 9, colorCount: 6, gateCount: 8,
    walls: [5, 7], locks: [4, 6], rails: [9, 15],
    anchors: [5, 9], bulky: [4, 8], duals: [2, 4],
    sharedGates: [1, 3],
    jokers: 1, demandTarget: 16,
  },
  {
    id: 15, tier: 'demanding',
    name: { fr: 'Honey Acacia', en: 'Honey Acacia', es: 'Honey Acacia', it: 'Honey Acacia', zh: 'Honey Acacia' },
    difficulty: { fr: 'impitoyable', en: 'merciless', es: 'despiadado', it: 'spietato', zh: '无情' },
    hue: 55,
    palette: ['#c98fae', '#8299d4', '#83c0b0', '#cfbc84', '#9f92d2', '#cf9a95'],
    novelty: null,
    introduces: { fr: 'Plus de joker : rien pour desserrer la grille', en: 'No joker left to loosen the grid', es: 'Sin comodín: nada que afloje la cuadrícula', it: 'Niente jolly: nulla che allenti la griglia', zh: '没有万能方块可依靠' },
    W: 9, H: 10, colorCount: 6, gateCount: 8,
    walls: [5, 7], locks: [4, 6], rails: [9, 15],
    anchors: [6, 9], bulky: [4, 8], duals: [2, 4],
    sharedGates: [2, 3], wideGateRatio: 0.2,
    jokers: 0, demandTarget: 20,
  },
  {
    id: 16, tier: 'demanding',
    name: { fr: 'Amber Birch', en: 'Amber Birch', es: 'Amber Birch', it: 'Amber Birch', zh: 'Amber Birch' },
    difficulty: { fr: 'vertigineux', en: 'dizzying', es: 'vertiginoso', it: 'vertiginoso', zh: '眩目' },
    hue: 40,
    palette: ['#c88fa0', '#7ea6cc', '#7fc3a2', '#ccba7c', '#9c8ecd', '#cd9885'],
    novelty: null,
    introduces: { fr: 'Les plus vastes grilles du jeu', en: 'The largest grids in the game', es: 'Las cuadrículas más amplias del juego', it: 'Le griglie più vaste del gioco', zh: '全游戏最大的棋盘' },
    W: 9, H: 10, colorCount: 6, gateCount: 8,
    walls: [5, 8], locks: [4, 6], rails: [10, 16],
    anchors: [6, 10], bulky: [5, 9], duals: [2, 4],
    sharedGates: [2, 3], wideGateRatio: 0.2, minShapeSize: 2, density: [0.26, 0.33],
    jokers: 0, demandTarget: 26,
  },
  {
    id: 17, tier: 'demanding',
    name: { fr: 'Apricot Branch', en: 'Apricot Branch', es: 'Apricot Branch', it: 'Apricot Branch', zh: 'Apricot Branch' },
    difficulty: { fr: 'sans retour', en: 'no way back', es: 'sin retorno', it: 'senza ritorno', zh: '无路可退' },
    hue: 25,
    palette: ['#c98b9c', '#7ba2cc', '#7cc09f', '#cbb679', '#9a8aca', '#ca9482'],
    novelty: null,
    introduces: { fr: 'Des portes au comptage exact, et rien pour se rattraper', en: 'Gates counted to the cell, and nothing to fall back on', es: 'Puertas contadas al detalle y nada a lo que recurrir', it: 'Porte contate al millimetro e nulla su cui ripiegare', zh: '门的容量精确到格，毫无退路' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [5, 8], locks: [5, 7], rails: [10, 16],
    anchors: [7, 10], bulky: [5, 9], duals: [2, 4],
    sharedGates: [2, 4], wideGateRatio: 0.15, minShapeSize: 2, density: [0.27, 0.34],
    jokers: 0, demandTarget: 32,
  },
  {
    id: 18, tier: 'demanding',
    name: { fr: 'Red Berry', en: 'Red Berry', es: 'Red Berry', it: 'Red Berry', zh: 'Red Berry' },
    difficulty: { fr: 'nœud', en: 'knotted', es: 'enredado', it: 'intricato', zh: '纠缠' },
    hue: 5,
    palette: ['#c78ba6', '#7d9fd0', '#7ec3a8', '#c9b47e', '#9a8ccb', '#c99688'],
    novelty: null,
    introduces: { fr: 'Des blocs qui se gênent : il faut trouver l’ordre', en: 'Blocks that get in each other’s way: the order matters', es: 'Bloques que se estorban: hay que dar con el orden', it: 'Blocchi che si ostacolano: bisogna trovare l’ordine', zh: '方块彼此挡路：顺序才是关键' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [4, 7], locks: [4, 6], rails: [10, 16],
    anchors: [7, 11], bulky: [5, 9], duals: [0, 2],
    sharedGates: [2, 4], wideGateRatio: 0.15, minShapeSize: 2, density: [0.26, 0.32],
    jokers: 0, demandTarget: 40,
  },
  {
    id: 19, tier: 'demanding',
    name: { fr: 'Snow Willow', en: 'Snow Willow', es: 'Snow Willow', it: 'Snow Willow', zh: 'Snow Willow' },
    difficulty: { fr: 'inextricable', en: 'inextricable', es: 'inextricable', it: 'inestricabile', zh: '无解之局' },
    hue: 30,
    palette: ['#c4879c', '#7799c9', '#78bd9c', '#c4b075', '#9385c6', '#c58f80'],
    novelty: null,
    introduces: { fr: 'Chaque sortie en ferme une autre', en: 'Every exit closes another one', es: 'Cada salida cierra otra', it: 'Ogni uscita ne chiude un’altra', zh: '每开一门，另一门便闭' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [5, 8], locks: [5, 7], rails: [12, 18],
    anchors: [8, 12], bulky: [6, 10], duals: [0, 1],
    sharedGates: [3, 5], wideGateRatio: 0.1, minShapeSize: 2, density: [0.27, 0.33],
    jokers: 0, demandTarget: 48,
  },
  {
    id: 20, tier: 'punishing',
    name: { fr: 'Blush Plum', en: 'Blush Plum', es: 'Blush Plum', it: 'Blush Plum', zh: 'Blush Plum' },
    difficulty: { fr: 'cloisonné', en: 'partitioned', es: 'compartimentado', it: 'compartimentato', zh: '分隔' },
    hue: 345,
    palette: ['#c98fa4', '#849dc6', '#83bfa4', '#c8b47c', '#9c8dc4', '#c99a8a'],
    novelty: null,
    introduces: { fr: 'Des murs partout : l’espace se referme', en: 'Walls everywhere: the space closes in', es: 'Muros por doquier: el espacio se cierra', it: 'Muri ovunque: lo spazio si chiude', zh: '四处是墙，空间收紧' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [7, 10], locks: [3, 5], rails: [8, 13],
    anchors: [5, 8], bulky: [4, 7], duals: [0, 2],
    sharedGates: [2, 3],
    demandTarget: 56,
  },
  {
    id: 21, tier: 'punishing',
    name: { fr: 'Lavender Field', en: 'Lavender Field', es: 'Lavender Field', it: 'Lavender Field', zh: 'Lavender Field' },
    difficulty: { fr: 'enchaîné', en: 'chained', es: 'encadenado', it: 'concatenato', zh: '环环相扣' },
    hue: 275,
    palette: ['#c58ba0', '#7fa3cb', '#7cc0a8', '#c6b17e', '#9689c8', '#c69688'],
    novelty: null,
    introduces: { fr: 'Des verrous qui s’ouvrent l’un après l’autre', en: 'Locks that open one after another', es: 'Cerrojos que se abren uno tras otro', it: 'Serrature che si aprono una dopo l’altra', zh: '锁需依次开启' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [4, 7], locks: [6, 9], rails: [8, 13],
    anchors: [5, 9], bulky: [4, 7], duals: [0, 2],
    sharedGates: [2, 4],
    demandTarget: 64,
  },
  {
    id: 22, tier: 'punishing',
    name: { fr: 'Blue Hydrangea', en: 'Blue Hydrangea', es: 'Blue Hydrangea', it: 'Blue Hydrangea', zh: 'Blue Hydrangea' },
    difficulty: { fr: 'rigide', en: 'rigid', es: 'rígido', it: 'rigido', zh: '僵硬' },
    hue: 225,
    palette: ['#d2947e', '#86aec2', '#93c191', '#ccb377', '#a292c0', '#cc9b7e'],
    novelty: null,
    introduces: { fr: 'Presque rien ne circule librement', en: 'Almost nothing moves freely', es: 'Casi nada circula libremente', it: 'Quasi nulla si muove liberamente', zh: '几乎无一可自由移动' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [4, 6], locks: [4, 6], rails: [13, 19],
    anchors: [9, 14], bulky: [3, 6], duals: [0, 2],
    sharedGates: [2, 3],
    demandTarget: 72,
  },
  {
    id: 23, tier: 'punishing',
    name: { fr: 'Winter Frost', en: 'Winter Frost', es: 'Winter Frost', it: 'Winter Frost', zh: 'Winter Frost' },
    difficulty: { fr: 'pesant', en: 'weighty', es: 'pesado', it: 'pesante', zh: '沉重' },
    hue: 200,
    palette: ['#c08bb0', '#8296cc', '#7fbdac', '#c4ad7d', '#9887c9', '#c1948f'],
    novelty: null,
    introduces: { fr: 'Les encombrants saturent les portes', en: 'Heavy blocks saturate the gates', es: 'Los voluminosos saturan las puertas', it: 'Gli ingombranti saturano le porte', zh: '笨重方块塞满门口' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [4, 7], locks: [4, 6], rails: [8, 12],
    anchors: [5, 9], bulky: [9, 14], duals: [0, 2],
    sharedGates: [2, 4],
    demandTarget: 80,
  },
  {
    id: 24, tier: 'punishing',
    name: { fr: 'Bamboo Breeze', en: 'Bamboo Breeze', es: 'Bamboo Breeze', it: 'Bamboo Breeze', zh: 'Bamboo Breeze' },
    difficulty: { fr: 'trouble', en: 'murky', es: 'turbio', it: 'torbido', zh: '混沌' },
    hue: 145,
    palette: ['#c68fa2', '#84a8c9', '#88c495', '#c9b57a', '#9c8ec6', '#c59a85'],
    novelty: null,
    introduces: { fr: 'Presque chaque porte sert deux couleurs', en: 'Nearly every gate serves two colours', es: 'Casi cada puerta sirve a dos colores', it: 'Quasi ogni porta serve due colori', zh: '几乎每道门都通两色' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [4, 7], locks: [4, 6], rails: [9, 14],
    anchors: [6, 10], bulky: [5, 8], duals: [0, 2],
    sharedGates: [5, 7],
    demandTarget: 88,
  },
  {
    id: 25, tier: 'punishing',
    name: { fr: 'Yellow Broom', en: 'Yellow Broom', es: 'Yellow Broom', it: 'Yellow Broom', zh: 'Yellow Broom' },
    difficulty: { fr: 'inextricable', en: 'tangled', es: 'intrincado', it: 'intricato', zh: '纠缠难解' },
    hue: 55,
    palette: ['#bd88a4', '#7d95c6', '#79bba6', '#c0aa78', '#9184c4', '#bf9086'],
    novelty: null,
    introduces: { fr: 'De grosses pièces dans des couloirs étroits', en: 'Big pieces in narrow corridors', es: 'Piezas grandes en pasillos estrechos', it: 'Pezzi grandi in corridoi stretti', zh: '大块方块，窄小通道' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [7, 10], locks: [4, 6], rails: [9, 14],
    anchors: [7, 11], bulky: [5, 9], duals: [0, 2],
    sharedGates: [3, 5],
    demandTarget: 96,
  },
  {
    id: 26, tier: 'punishing',
    name: { fr: 'Wheat Field', en: 'Wheat Field', es: 'Wheat Field', it: 'Wheat Field', zh: 'Wheat Field' },
    difficulty: { fr: 'implacable', en: 'relentless', es: 'implacable', it: 'implacabile', zh: '毫不留情' },
    hue: 40,
    palette: ['#c4877f', '#83a3c0', '#84bd93', '#c3ae76', '#9787c2', '#c3927c'],
    novelty: null,
    introduces: { fr: 'Tout se déplace sur un rail ou une flèche', en: 'Everything runs on a rail or an arrow', es: 'Todo se mueve sobre un raíl o una flecha', it: 'Tutto scorre su un binario o una freccia', zh: '一切皆循轨与箭' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [4, 7], locks: [5, 7], rails: [15, 21],
    anchors: [11, 16], bulky: [4, 8], duals: [0, 2],
    sharedGates: [3, 5],
    demandTarget: 104,
  },
  {
    id: 27, tier: 'punishing',
    name: { fr: 'Copper Beech', en: 'Copper Beech', es: 'Copper Beech', it: 'Copper Beech', zh: 'Copper Beech' },
    difficulty: { fr: 'compté', en: 'counted', es: 'contado', it: 'contato', zh: '分秒必争' },
    hue: 25,
    palette: ['#bd8697', '#7a9cc4', '#77bba2', '#bfa974', '#8f81be', '#bd8f81'],
    novelty: null,
    introduces: { fr: 'Chaque porte est comptée à la case près', en: 'Every gate counted to the cell', es: 'Cada puerta contada al detalle', it: 'Ogni porta contata al millimetro', zh: '每道门的容量精确到格' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [5, 8], locks: [5, 7], rails: [10, 15],
    anchors: [8, 12], bulky: [6, 10], duals: [0, 2],
    sharedGates: [3, 5],
    demandTarget: 112,
  },
  {
    id: 28, tier: 'punishing',
    name: { fr: 'Crimson Vine', en: 'Crimson Vine', es: 'Crimson Vine', it: 'Crimson Vine', zh: 'Crimson Vine' },
    difficulty: { fr: 'sans complaisance', en: 'unforgiving', es: 'sin concesiones', it: 'senza sconti', zh: '绝不宽容' },
    hue: 5,
    palette: ['#b9839f', '#7692c0', '#73b79e', '#bba572', '#8b7dba', '#b98b7d'],
    novelty: null,
    introduces: { fr: 'Tout le jeu à la fois, sans rien pour souffler', en: 'The whole game at once, no let-up', es: 'Todo el juego a la vez, sin respiro', it: 'Tutto il gioco insieme, senza tregua', zh: '全部机制齐上，毫无喘息' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [6, 9], locks: [6, 8], rails: [12, 18],
    anchors: [9, 14], bulky: [7, 11], duals: [0, 2],
    sharedGates: [4, 6],
    demandTarget: 122,
  },
  {
    id: 29, tier: 'punishing',
    name: { fr: 'Silver Mist', en: 'Silver Mist', es: 'Silver Mist', it: 'Silver Mist', zh: 'Silver Mist' },
    difficulty: { fr: 'vertigineux', en: 'dizzying', es: 'vertiginoso', it: 'vertiginoso', zh: '令人眩晕' },
    hue: 30,
    palette: ['#b57f9b', '#728ebc', '#6fb39a', '#b7a16e', '#8779b6', '#b58779'],
    novelty: null,
    introduces: { fr: 'Les grilles les plus retorses du jeu', en: 'The most devious grids in the game', es: 'Las cuadrículas más retorcidas del juego', it: 'Le griglie più insidiose del gioco', zh: '全游戏最刁钻的棋盘' },
    W: 9, H: 11, colorCount: 6, gateCount: 8,
    walls: [6, 9], locks: [6, 9], rails: [13, 19],
    anchors: [10, 15], bulky: [8, 12], duals: [0, 2],
    sharedGates: [4, 7],
    demandTarget: 135,
  },];

export const TOTAL_LEVELS = REALMS.length * LEVELS_PER_REALM;

/** The realm level `n` belongs to (1-indexed). */
export function realmOf(n) {
  return REALMS[Math.min(REALMS.length - 1, Math.floor((n - 1) / LEVELS_PER_REALM))];
}
