# (cle, nom affiche, sujet, palette des fleurs, papier RVB)
# Ordonnes pour que la teinte tourne doucement et reboucle du 30e au 1er.
MONDES = [
    ("01", "Peaceful Sakura",  "small soft pink sakura blossoms",              "dusty pink and blush pastel colours",        (247, 236, 234)),
    ("02", "Blush Plum",       "small deep pink plum blossoms",                "deep blush pink and soft rose pastel colours",(246, 233, 236)),
    ("03", "Quiet Camellia",   "small pink camellia flowers",                  "soft rose and powder pink pastel colours",   (247, 234, 238)),
    ("04", "Wild Rose",        "small pale wild rose flowers",                 "pale rose and cream pastel colours",         (248, 236, 240)),
    ("05", "Soft Peony",       "small powdery pink peony flowers",             "powder pink and mauve pink pastel colours",  (246, 234, 241)),
    ("06", "Lilac Drift",      "small lilac flower clusters",                  "soft lilac pastel colours",                  (242, 234, 243)),
    ("07", "Wisteria Veil",    "long hanging wisteria clusters in pale mauve", "soft mauve and lavender pastel colours",     (238, 232, 244)),
    ("08", "Violet Iris",      "small violet iris flowers",                    "soft violet and periwinkle pastel colours",  (236, 232, 245)),
    ("09", "Lavender Field",   "small lavender flower spikes",                 "lavender and pale indigo pastel colours",    (234, 233, 246)),
    ("10", "Blue Lys",         "small pale blue lily flowers",                 "powder blue and periwinkle pastel colours",  (228, 234, 245)),
    ("11", "Morning Glory",    "small blue morning glory flowers",             "soft cornflower blue pastel colours",        (226, 236, 245)),
    ("12", "Forget Me Not",    "tiny pale blue forget me not flowers",         "pale sky blue pastel colours",               (227, 238, 245)),
    ("13", "Winter Frost",     "tiny frosted buds under light snow",           "cool pale blue and white pastel colours",    (230, 239, 245)),
    ("14", "Snow Willow",      "slender willow twigs under soft snow",         "white and pale blue grey pastel colours",    (235, 240, 243)),
    ("15", "Silver Mist",      "tiny silver grey seed pods",                   "silver grey and pale pearl pastel colours",  (238, 240, 240)),
    ("16", "Eucalyptus Calm",  "small round sage eucalyptus leaves",           "soft sage green pastel colours",             (233, 241, 237)),
    ("17", "Sage Fern",        "small delicate fern fronds",                   "pale sage and celadon pastel colours",       (232, 241, 232)),
    ("18", "Green Maple",      "small fresh green maple leaves",               "tender green and celadon pastel colours",    (234, 242, 230)),
    ("19", "Bamboo Breeze",    "slender bamboo leaves",                        "soft bamboo green pastel colours",           (236, 242, 228)),
    ("20", "Olive Grove",      "small narrow olive leaves",                    "muted olive and pale khaki pastel colours",  (240, 241, 226)),
    ("21", "Golden Ginkgo",    "small golden fan shaped ginkgo leaves",        "warm gold and pale amber pastel colours",    (244, 238, 222)),
    ("22", "Mimosa Sun",       "tiny round fluffy yellow mimosa flowers",      "mimosa yellow and pale wheat pastel colours",(246, 238, 219)),
    ("23", "Honey Acacia",     "small honey coloured acacia flowers",          "honey yellow and cream pastel colours",      (247, 239, 222)),
    ("24", "Amber Birch",      "small amber birch leaves",                     "amber and pale wheat pastel colours",        (247, 237, 224)),
    ("25", "Apricot Branch",   "small apricot coloured leaves",                "soft apricot pastel colours",                (248, 235, 226)),
    ("26", "Autumn Elm",       "small orange elm leaves",                      "soft orange and terracotta pastel colours",  (248, 234, 227)),
    ("27", "Copper Beech",     "small copper beech leaves",                    "copper and dusty rose pastel colours",       (248, 233, 228)),
    ("28", "Winter Maple",     "small red maple leaves",                       "muted crimson and dusty rose pastel colours",(247, 233, 230)),
    ("29", "Red Berry",        "tiny red berries on bare twigs",               "soft red and pale rose pastel colours",      (248, 234, 232)),
    ("30", "Apple Blossom",    "small white apple blossoms with pale hearts",  "creamy white and soft blush pastel colours", (248, 238, 234)),
]
